# Generated by Django 6.0.7 on 2026-07-21 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCategoria', models.CharField(max_length=100, verbose_name='Nome da categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Consumidor',
                'verbose_name_plural': 'Consumidores',
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do usuário')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCompra', models.DateTimeField(verbose_name='Data da compra')),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total')),
                ('status', models.CharField(max_length=30, verbose_name='Status')),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consumidor', verbose_name='Consumidor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoEstabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(verbose_name='Nota')),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('dataAvaliacao', models.DateTimeField(verbose_name='Data da avaliação')),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consumidor', verbose_name='Consumidor')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estabelecimento', verbose_name='Estabelecimento')),
            ],
            options={
                'verbose_name': 'Avaliação de Estabelecimento',
                'verbose_name_plural': 'Avaliações de Estabelecimentos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do produto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('precoOriginal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('dataValidade', models.DateField(verbose_name='Data de validade')),
                ('imagem', models.CharField(max_length=255, verbose_name='Imagem')),
                ('status', models.CharField(max_length=30, verbose_name='Status')),
                ('qtdEstoque', models.IntegerField(verbose_name='Quantidade em estoque')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria', verbose_name='Categoria')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estabelecimento', verbose_name='Estabelecimento')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('precoUnitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compra', verbose_name='Compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item da Compra',
                'verbose_name_plural': 'Itens da Compra',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(verbose_name='Nota')),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('dataAvaliacao', models.DateTimeField(verbose_name='Data da avaliação')),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consumidor', verbose_name='Consumidor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Avaliação de Produto',
                'verbose_name_plural': 'Avaliações de Produtos',
            },
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='consumidor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário'),
        ),
    ]
