# Generated by Django 5.2.17 on 2026-09-04 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoestabelecimento',
            name='consumidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_estabelecimentos', to='app.consumidor', verbose_name='Consumidor'),
        ),
        migrations.AlterField(
            model_name='avaliacaoestabelecimento',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='app.estabelecimento', verbose_name='Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='avaliacaoproduto',
            name='consumidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_produtos', to='app.consumidor', verbose_name='Consumidor'),
        ),
        migrations.AlterField(
            model_name='avaliacaoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='app.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='consumidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='app.consumidor', verbose_name='Consumidor'),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumidor', to='app.usuario', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimento', to='app.usuario', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.compra', verbose_name='Compra'),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_compra', to='app.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='app.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='app.estabelecimento', verbose_name='Estabelecimento'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem'),
        ),
    ]
