# Generated by Django 6.1.1 on 2026-09-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_notificacaoavaliacao'),
        ('app', '0009_produto_preco_promocional'),
    ]

    operations = [
    ]
